version: '3'
services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: portal-server
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - '80:80'
    links:
      - api:api
      - app:app
  app:
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile.dev
    image: portal-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./../app:/usr/src/app
    ports:
      - '3000:3000'
  api:
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: portal-api
    environment:
      - DB_NAME=myappdb
      - DB_USER=myappuser
      - DB_PASSWORD=myapppassword
      - DB_HOST="db"
      - DB_PORT=5432
      - NODE_ENV=development
    links:
      - db:db
    volumes:
      - ./../api:/usr/src/api
    ports:
      - '8080'
    depends_on:
      - "db"
  db:
    build:
      context: ../.
      dockerfile: docker/db/Dockerfile.dev
    env_file: db/psql.env
    image: portal-db
    env_file: ../docker/db/psql.env
    ports:
      - '5431:5432'